---
- hosts: fch01
  remote_user: root
  tasks:
   - name: copy file to remote
     copy:
       src: /etc/ansible/playbooks/ctrl-mnt.sh
       dest: /tmp/ctrl-mnt.sh
       owner: root
       group: root
       mode: 0744

   - name: fix nfs mount of nas
     lineinfile: 
       dest=/etc/fstab
       regexp='^nfsserver'
       line="nas:/volume1/chiellino/xCAT /virtual/mnt    nfs     rsize=8192,wsize=8192,timeo=14,intr"
       state=present
     notify: umount nfs mount
   - name: fix nfs mount of nfsserver
     lineinfile: 
       dest=/etc/fstab
       regexp='^nas'
       line="nfsserver:/volume1/chiellino/vmware /virtual/mnt1    nfs     rsize=8192,wsize=8192,timeo=14,intr"
       state=present
     notify: umount nfs mount
  handlers:
   - name: umount nfs mount
     command: "/tmp/ctrl-mnt.sh off"
     register: umount
     notify: mount nfs mount

   - name: mount nfs mount
     command: "/tmp/ctrl-mnt.sh on"
     when: umount.changed
