---
- hosts: all
  remote_user: root
  tasks:
  - name: ensure ntp is at the latest version
    yum:
      name: ntp
      state: latest
  - name: ensure ntp is running
    service:
      name: ntpd
      state: started
